### ISSUE TITLE
values not in iobroker object tree

### ISSUE THREAD

**Issue by matze-dev** [hacki11/ioBroker.bsblan#155]
Hello,
I use the olimex ESP32 Board with the BSB-LAN-Adapter. 
I wat to retrieve the values via BSB-LAN Adapter in iobroker.
Could you please tell me, how I can implement the BSB-vlues in the object tree? I only see value "Betriebsart_(700)". I need the values 1600 (Trinkwasser) and 8700 (Aussentemperatur) too. How can these values be implemented in the adapter?
Thanks in advance

**Comment by hacki11** [comment]
Just add the IDs in the adapter configuration

**Comment by matze-dev** [comment]
The adapter is aleady installed, therefore I must add the values afterwards. Where can this be done?
![grafik](https://user-images.githubusercontent.com/71457696/202762842-5f68d458-1ec5-4a3a-8fac-6aa36e25daeb.png)

**Comment by hacki11** [comment]
You are in object view, change to instance view where you configured the IP address of the bsblan adapter, too. There is a field where you can enter all IDs you need.

**Comment by matze-dev** [comment]
Thanx, now it works!!! The values must separated by comma - it was not obviously in the first preview.

**Comment by hacki11** [comment]
Space or new line separated should also work.
