### ISSUE TITLE
Add support for INF 10003 "Außentemperatur" too

### ISSUE THREAD

**Issue by tetzlav** [hacki11/ioBroker.bsblan#19]
If i add INF parameter 10003 to overwrite "Außentemperatur" if get in serial console:

> POST /JS HTTP/1.1
/JS
Setting parameter 10003 to 17 with type 1
setting line: 10003 val: 01 04 40
Duration until answer received: 265
Message received, but not for us:
DC 8A 00 0B 06 3D 0D 05 19 4F 8C
Duration until answer received: 340
Message received, but not for us:
DC 80 0A 0E 07 0D 3D 05 19 00 0D 9D 9B C3
No answer for this send telegram:
DC C2 00 0E 03 05 00 02 1F 01 04 40 C1 5E
set failed

It seems to bee the wrong data type.

**Comment by tetzlav** [comment]
I changed the writetype to 0 in config.js, that works. 
There i notized that the parameter 8700 (Außentemperatur) is also "rw": true, "writeType": 1. Thats wrong. Its readonly...

**Comment by hacki11** [comment]
Thanks for the feedback, should be fixed easily.
PR appreciated, otherwise i will do it if i find some time

**Comment by tetzlav** [comment]
> There i notized that the parameter 8700 (Außentemperatur) is also "rw": true, "writeType": 1. Thats wrong. Its readonly...

^^

**Comment by hacki11** [comment]
I made the changes in current master, please install from github and verify the issue.
