### ISSUE TITLE
make INF Parameter writeonly

### ISSUE THREAD

**Issue by tetzlav** [hacki11/ioBroker.bsblan#20]
The virtual parameter 10000-10004 are only for broadcasting values for room or outer temperature.
This parameter should be writeonly or maybe better the readings should be mapped to 10000->8740, 10001->8770 and 10003/10004->8700?

While writing 10000 i got

>POST /JS HTTP/1.1
/JS
Setting parameter 10000 to 23.1 with type 0
setting line: 10000 val: 05 C6 00
LAN->HEIZ INF      3D2D0215 05 C6 00
DC C2 00 0E 02 3D 2D 02 15 05 C6 00 BB 7F
GET /JQ=10000 HTTP/1.1
/JQ=10000
Duration until answer received: 74
LAN->HEIZ QUR 10000 Benutzerdefiniert -  Raumtemperatur 1:
DC C2 00 0B 06 3D 2D 02 15 79 5B
HEIZ->LAN ERR 10000 Benutzerdefiniert -  Raumtemperatur 1: error 7 (parameter not supported)
DC 80 42 0C 08 2D 3D 02 15 07 A2 8B

**Comment by hacki11** [comment]
I prefer setting the objects write only, due to the better backwards compatibility
