### ISSUE TITLE
Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason

### ISSUE THREAD

**Issue by jh2k19** [hacki11/ioBroker.bsblan#239]
![image](https://github.com/hacki11/ioBroker.bsblan/assets/51288287/42a52571-06e8-4042-864c-6f86f85eeb32)

**Comment by jh2k19** [comment]
ioBroker BSB-LAN-Adapter, Version 0.3.1
BSB-LAN, Version 3.3.2-20231115201023


If i delete the Values 2020x.x in ioB Objects and delete the 20200.1/20201.1 in ioB Adapter Config there is no more warning for Adapter Objects loke 2020x.x

But if i delete only the Values 2020x.x in ioB Objects it will be created automaticaly new but the debug Log shows the warn again as before.

debug on and deleted 20200.1/20201.1 in Adapter Config
[1.txt](https://github.com/hacki11/ioBroker.bsblan/files/14546427/1.txt)

debug on and deleted 20200.1/20201.1 in Adapter Config and in BSB-LAN Webinterface set BME280 sensors from 2 to 0
[2.txt](https://github.com/hacki11/ioBroker.bsblan/files/14546448/2.txt)

Hope that helps to find the issue.
Let me know what i can do to help to fix the problem.
Thanks

**Comment by hacki11** [comment]
I guess it is also related to https://github.com/hacki11/ioBroker.bsblan/issues/238

Currently support for .x or !x is not implemented so the behaviour is currently undefined. Support for that needs to be added within the adapter.

**Comment by hacki11** [comment]
Can you try if the following will fix your issue? 
Install from custom github:
https://github.com/hacki11/ioBroker.bsblan/tree/multidimensional-id

I have sanitized the . in the key so it won't create a folder which should be an object.

**Comment by jh2k19** [comment]
Now i've installed BSB-LAN Version: 3.3.4-20240301014054 from freetz and ioB BSB-LAN Adapter V 0.3.2
Here is the result:

[1.txt](https://github.com/hacki11/ioBroker.bsblan/files/14549825/1.txt)


![image](https://github.com/hacki11/ioBroker.bsblan/assets/51288287/72eccefb-845d-4efa-a6a1-8c445b6663d4)

**Comment by hacki11** [comment]
Despite the warning it looks better, doesn't it? Is the data coming as expected for you? Then I just need to verify why the warning is popping up here.

**Comment by jh2k19** [comment]
Unfortunately no. Previously the data came correctly despite the warning status in the log. Now the current values ​​are no longer fetched.

**Comment by jh2k19** [comment]
One more note. This issue was about the constant and independent termination and restart of the adapter. According to the log, this problem is still there. The adapter always shows this. It always turns red and green. Can we rename or combine issues #219 and #239.

**Comment by hacki11** [comment]
https://forum.iobroker.net/topic/53414/zigbee-instanz-scheduled-restart/5

The log line "scheduled restart" looks like you configured the adapter to be restarted regularly. Can you check that?
![image](https://github.com/hacki11/ioBroker.bsblan/assets/15319906/eb21462c-f6bf-4595-b600-7fcd69b5a318)
I guess the adapter should then run stable. 

Regarding the value I need to verify

**Comment by hacki11** [comment]
I have updated the branch with support for <id>.<x>, can you check if this works for you now?

Responses of parameters with .0 are not containing .0 anymore, therfor a matching was not possible.
Responses of parameters with .1 and higher are containing the .x.

This special behavior was needed to be implemented. The result is, that the .0 is also omitted within iobrokers object view.

**Comment by jh2k19** [comment]
Great work. Everything works as expected. No warning messages and no errors. And yes, scheduled restart was configured. I don't know if that was me. I'm sorry I didn't see that. 
Thank you very much for the great support

[1.txt](https://github.com/hacki11/ioBroker.bsblan/files/14550781/1.txt)

![image](https://github.com/hacki11/ioBroker.bsblan/assets/51288287/16289e37-57ff-4dee-9d7d-f64ffa54f0e0)

**Comment by hacki11** [comment]
Thank you for bringing this to the table so I could improve the adapter. I will make a release soon

**Comment by hacki11** [comment]
solved in v0.3.2
