### ISSUE TITLE
 No more values ​​from 20200.1 and 20201.1

### ISSUE THREAD

**Issue by jh2k19** [hacki11/ioBroker.bsblan#243]
Unfortunately, with versions 0.3.2 and 0.3.3 there are no longer any values ​​from 20200.1 and 20201.1

VG Jürgen

**Comment by hacki11** [comment]
Can you provide a log so I can see what's going on?

**Comment by hacki11** [comment]
Did you delete the two objects from object tree after updating from the dev branch to the latest version? I'm not 100% sure if it's needed but definitely worth a try.

**Comment by jh2k19** [comment]
Sorry, I must have had a pause in my thoughts. 
So, it worked with V 0.3.2 and deleting the objects. 
Sorry again. VG Jürgen

**Comment by hacki11** [comment]
No worries, glad it is working for you now

**Comment by jh2k19** [comment]
Oh yes that's true. 
See you next time. 
VG Jürgen
