### ISSUE TITLE
MQTT auto discovery possible for ioBroker?

### ISSUE THREAD

**Issue by fredlcore** [hacki11/ioBroker.bsblan#249]
I'm not sure if this is the right place to ask/discuss this, maybe it has nothing to with your connector:
I have implemented MQTT auto discovery (as supported by Home Assistant) into BSB-LAN. I was wondering if ioBroker also supports something like this and/or this would be helpful for your adapter. It basically sends a lot of JSON structures with definitions for each parameter to the MQTT broker on a special topic, and Home Assistant then creates the corresponding entities from these. Combined with the fact that BSB-LAN now sends the result of every query also to the broker, you can get a full set of parameters and their data with just two URL calls (`/M1` and `/0-21000`).
If that would be of use for ioBroker users as well, let me know and I'll add any relevant information for ioBroker there as well.

**Comment by hacki11** [comment]
Iobroker has a mechanism to detect devices in your network and automatically download and configure the necessary adapters for it. I provided an implementation for bsblan based on mdns which is supported by BSBLAN. So there is already a good way in place.

But I see more and more MQTT features within BSBLAN which would also allow a direct integration without an adapter. MQTT is of course a heavy used interface also for iobroker. Perhaps BSBLAN can also be used now without an adapter which would be great. We should definitely try to see if it is working or what's missing for this.

**Comment by fredlcore** [comment]
Ok, understood - since I haven't used ioBroker so far, I wasn't sure if your ioBroker-adapter was necessary for processing the data or to connect to BSB-LAN. Apparently, it does all that and more, and with less setup necessary for the user, so I guess that's even better than the MQTT-based detection, because also that one (on Home Assistant at least) supports less information about the parameters compared to what you can acquire based on the JSON-API of BSB-LAN (which I think you are using). So if all of that runs automatically in ioBroker now thanks to your adapter, I guess there is no need to change anything. But if you think otherwise or see room for improvement, please let me know.

**Comment by hacki11** [comment]
Until a full MQTT Support was/is realized, the adapter definitely is needed to connect the BSBLAN. The more MQTT features are coming the more it can be likely that a direct connection can be realized. Currently I do not know the difference wrt. User experience and feature set. I would keep up the development as long as it is broadly used tbh. 

For the Auto discovery we could check how it interops with iobroker but that topic I see unrelated to this adapter as it would not be needed in this toolchain. I would call that topic interoperability between BSBLAN and iobroker.

**Comment by fredlcore** [comment]
Ok, I don't think it makes much sense to make any changes then - as I said, I didn't know if there was any parameter detection already available. And I'm also not sure whether I could easily add additional information because at times, the Home Assistant detection did not like it when additional information was provided (or I haven't really figured out where the problem was back then). So if you main access way is through the JSON API, I would recommend to stick with that one, rather than adding another component (MQTT) to the equation. Thanks again for your work on this and hope you'll keep it up in the future!
