### ISSUE TITLE
writing temperature 10003 fails with Error writing value: Could not set value: "{"10003":{"status":0}}"

### ISSUE THREAD

**Issue by tetzlav** [hacki11/ioBroker.bsblan#273]
updated adapter from v0.2.0 to v0.3.4
bsb_lan firmware version: 4.2.25-20241121012751

try to write parameter 10003
> Error writing value: Could not set value: "{"10003":{"status":0}}"

serial log:

> POST /JS HTTP/1.1
setting line: 10003 val: 01 00 40
LAN->HEIZ SET 10003.0 Benutzerdefiniert - Außentemperatur: 1.0 °C
DC C2 00 0E 03 00 05 02 1F 01 00 40 37 3C
Publishing to topic: BSB-LAN-Therme/0/64/10003/status
Payload: 1.0
Successfully published...
HEIZ->LAN NACK 10003.0 Benutzerdefiniert - Außentemperatur: FIXPOINT len !=3: 05
DC 80 42 0C 05 05 00 02 1F 05 3C B7
set failed NACK
Setting parameter 10003 to "1" with type 1 to destination 0

I think it has something to do with

>[v2.2.2](https://github.com/fredlcore/BSB-LAN/releases/tag/v2.2.2)
Backport of changed meaning of FL_SPECIAL_INF. Room temperature parameters 10000, 10001 and 10002 must now have the FL_SPECIAL_INF flag added. Outside temperature simulation (10003 or 10017) must have it removed, the same goes for the Weishaupt room temperatur parameters.

and
>[v4.0](https://github.com/fredlcore/BSB-LAN/releases/tag/v4.0)
    ATTENTION: BREAKING CHANGE! Room temperature parameter 10000, 10001 and 10002 must now have the additional flag FL_SPECIAL_INF, otherwise setting temperature will not work!
    ATTENTION: BREAKING CHANGE! Outside temperature simulation parameter 10017 must have FL_SPECIAL_INF flag removed, otherwise setting temperature will not work!

**Comment by hacki11** [comment]
If they talk about this flag, it sounds like it must be added in bsblan firmware. Did you check if the flag is set in your firmware?
