### ISSUE TITLE
Connection state updates very often 

### ISSUE THREAD

**Issue by manoloxxl** [hacki11/ioBroker.bsblan#274]
**Describe the bug**  
I am running a check against the state "connection". When the device is not available a message is send, and also when the device is rechable again.

But the state is not stable, it is switching from available to not available every status update (10 seconds in my case). But as far as i can see, the device is online the hole time.

I am unsure if there should be time buffer before the device is shown as offline or if there is an issue in the code that is udating the connection state.

**To Reproduce**  
Just reboot device and adapter and take a look in the history of the data point.

**Expected behavior**  
A stable status in the data point

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/9d035276-143f-43b0-bc4e-36bbaed5d8cf)

**Versions:**  
 - Adapter version: 0.34
 - JS-Controller version: 7.03
 - Node version: v20.17.0
 - Operating system: Docker

**Additional context**  
-

**Comment by hacki11** [comment]
Can you add the adapter log? If Info level is not showing suspicious entries please set it to debug.

**Comment by manoloxxl** [comment]
It's allways this part:

	2024-12-22 19:00:27.399	info	Connection established successfully

bsblan.0
2024-12-22 19:00:17.134	error	Connection failed

bsblan.0
2024-12-22 19:00:17.134	error	TypeError: Cannot read properties of undefined (reading 'replace') at Bsblan.parseUnit (/opt/iobroker/node_modules/iobroker.bsblan/main.js:440:14) at Bsblan.set24hAvgObject (/opt/iobroker/node_modules/iobroker.bsblan/main.js:339:28) at Bsblan.set24hAverages (/opt/iobroker/node_modules/iobroker.bsblan/main.js:369:24) at /opt/iobroker/node_modules/iobroker.bsblan/main.js:109:37 at async Bsblan.update (/opt/iobroker/node_modules/iobroker.bsblan/main.js:103:9)

bsblan.0
2024-12-22 19:00:17.133	error	Cannot read properties of undefined (reading 'replace')


BUT, i have seen that also the MQTT connection is nt stable. Let me go to most recent version auf BSB-Lan, maybe there is an issue on my device as i have seen that we had a general power loss today in my house.

**Comment by hacki11** [comment]
There was a change regarding the average values. What bsblan firmware version do you have? Updating is definitely a good idea, I hope your board is still compatible.

**Comment by manoloxxl** [comment]
Hi, after uploading the latest version the board is working and the behaviour with the state is not longer present. Sorry, it seems the issue was on my side.

Just to complete this issue:
- Error was in 4.2.27
- now i am on 4.2.46-20241220005136

But again, i do not think it was an iobroker adapter or BSB-Lan issue. Maybe the power loss killed something. 


If you want, you can close this issue.

**Comment by hacki11** [comment]
Happy to hear it works again!

**Comment by manoloxxl** [comment]
Hi @hacki11 ,

I reopened this issue because i was running some checks with this "bsblan.0.info.connection" data point and i think there is a issue in the handling of the connection state.

What i did:
- i am running a BSB-Lan on Olimex POE, connected with LAN/POE
- build good running BSB-LAN, iobroker and your adapter.
- state shows "true"
- Monitor the bsblan.0.info.connection datapoint
- disconnect the bsb-lan device from LAN
- check the status change of the bsblan.0.info.connection

As you can see in my screeenhot the adapter changes the state from true to false to true to false... But the adapter is never reachable. So it can not be "true":

![image](https://github.com/user-attachments/assets/7e029838-6cf5-4f2d-b311-29a544d8f1fd)

In the log i can see that the adapter can establish a connection with the not connected device:

![image](https://github.com/user-attachments/assets/c7ca21a8-a0a9-4008-90c1-996f55931b17)

But this must bew wrong - the device is not connected.

Maybe there is a issue in the state handling for this data point?


Best regards
Manuel

**Comment by hacki11** [comment]
It looks indeed unexpected. I will have a look into the health state management.
