### ISSUE TITLE
Title too long

### ISSUE THREAD

**Issue by klein0r** [hacki11/ioBroker.bsblan#28]
Please change the translated title to a shorter version

https://github.com/hacki11/ioBroker.bsblan/blob/275a1245d77af58376d02736fcf978286e8bea19/io-package.json#L56-L59

**Comment by hacki11** [comment]
Can you provide a reason for that?

**Comment by klein0r** [comment]
Because

- there is no difference to the description
- and the ioBroker developer guideline says, that the title should not contain "ioBroker"

Otherwise any adapter can be renamed to "Connects .... with ioBroker" 😄

**Comment by hacki11** [comment]
https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md

Regarding the official requirements only the languages are missing. That's because gulp is not integrated yet but feel free to put a PR for that.

Where did you get those requirements?

**Comment by klein0r** [comment]
I've added an issue that the adapter checker should also check the titleLang Attribute (and not just the title).

Currently, it looks like this:

<img width="646" alt="Screenshot 2021-02-26 at 15 32 31" src="https://user-images.githubusercontent.com/1959049/109312958-f26a5c80-7847-11eb-98f9-6695b815c59a.png">

Which makes no sense. But if you say that this is the intended behavior, I will close this issue.

**Comment by hacki11** [comment]
Feel free to reopen when the requirement is officially rolled out. But I think Adapter checker will open automatically then :)

**Comment by klein0r** [comment]
> You are right, that looks pretty duplicate here

Yes, that was the reason for this issue. Feel free to fix it before the adapter checker will complain about it 😄

**Comment by hacki11** [comment]
I will do with the next fix or feature update
