### ISSUE TITLE
Cannot read Date/Time in NodeRed because of slash in ioBroker ID

### ISSUE THREAD

**Issue by Eldarion85** [hacki11/ioBroker.bsblan#75]
Hi there,
I have the problem that NodeRed cannot read the "Date/Time" from the ioBroker. I can select the item in the normal way via the project tree, but the status "not exist" appears after it has been deployed. As a test, I tried the separate items of the "Time" and "Year", it works without any problems. Unfortunately, the "Month/Day" item does not work either. I noticed that the only difference is that "Date/Time" and "Month/Day" contain a slash in the ioBroker ID.
I have created two own items with the IDs "with/slash" and "without_slash" to check this. My suspicion was confirmed. I can select both items in the NodeRed project tree, but only read the value of "without_slash". The output for "with/slash" is also "not exist".
Because I cannot change the ioBroker IDs of the BSB-LAN adapter, I would now have to create my own item without a slash and copy the value using a script. This is not a good solution. Can you maybe rename the ID "Date/Time" so that you can use it in NodeRed?

Thank you for your support!

![NodeRed](https://user-images.githubusercontent.com/90176159/132177731-c28a20c4-c89d-4c41-a4f7-309fc1696549.png)
![ioBroker](https://user-images.githubusercontent.com/90176159/132177733-17ab90d3-9e9e-4c96-b0d3-c45948638354.png)

**Comment by hacki11** [comment]
I get your pain, but slash is a allowed character for iobroker object names. It would be a breaking change for the users if i change it. Did you work around this issue?

**Comment by Eldarion85** [comment]
I have adjusted the translation file of the BSB-LAN adapter, which contains the names for the ioBroker. Now the names are shown without the slash and then it works.

This file needs to be customized:
BSB-LAN-master\BSB_LAN\localization\LANG_DE.h

![image](https://user-images.githubusercontent.com/90176159/183347391-f96db8ff-f8e9-493a-8bfe-73d67e33d6aa.png)
